apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-audit-metrics
  namespace: gatekeeper-system
  labels:
    app.kubernetes.io/name: gatekeeper
    gatekeeper.sh/operation: audit
spec:
  type: ClusterIP
  selector:
    app: gatekeeper
    gatekeeper.sh/operation: audit
  ports:
    - name: metrics
      port: 8888
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-controller-manager-metrics
  namespace: gatekeeper-system
  labels:
    app.kubernetes.io/name: gatekeeper
    gatekeeper.sh/operation: webhook
spec:
  type: ClusterIP
  selector:
    app: gatekeeper
    gatekeeper.sh/operation: webhook
  ports:
    - name: metrics
      port: 8888
      targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatekeeper
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - gatekeeper-system
  selector:
    matchLabels:
      app.kubernetes.io/name: gatekeeper
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
