apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: k8s-platform-reference
    platform.s34nj0hn.dev/owner: platform
    platform.s34nj0hn.dev/purpose: observability
