apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: reference-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
