apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - constraints/namespace-required-labels-template.yaml
  - constraints/namespace-required-labels-constraint.yaml
  - constraints/disallow-privileged-template.yaml
  - constraints/disallow-privileged-constraint.yaml
