apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: reference-grafana.s34nj0hn.dev
        service: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
      - service: http_status:404
