apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: k8s-platform-reference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
